In [1]:
import pandas as pd
project_data = pd.read_csv("project_data.csv", index_col=0)
project_data.head()

D:\Softwares\Anaconda\conda\lib\site-packages\pandas\core\computation\expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

,AAPL,DX-Y.NYB,HSI,QQQ,XLE,XLF,XLK,XLP,XLU,XLV,^FTSE
Date,,,,,,,,,,,
2000-01-06,0.721931,100.650002,15153.200195,68.762451,15.351149,11.529708,38.080395,13.271096,11.997421,20.878456,6447.200195
2000-01-07,0.756128,100.800003,15405.599609,77.267143,15.515195,11.720543,38.745140,14.112416,12.100608,21.133337,6504.799805
2000-01-10,0.742829,100.989998,15848.200195,79.413460,15.385676,11.513805,40.217052,13.795789,12.141886,23.294325,6607.700195
2000-01-11,0.704832,100.559998,15862.099609,75.550079,15.402951,11.322968,39.077492,13.795789,12.011181,22.673742,6518.899902
2000-01-12,0.662562,100.620003,15714.200195,73.886742,15.333877,11.545604,38.911304,13.868158,11.887353,22.296949,6532.799805

In [2]:
#Returns of individual columns
AAPL_daily_returns =project_data['AAPL'].pct_change()
DX_NYB_daily_returns =project_data['DX-Y.NYB'].pct_change()
HSI_daily_returns =project_data['HSI'].pct_change()
QQQ_daily_returns =project_data['QQQ'].pct_change()
XLE_daily_returns =project_data['XLE'].pct_change()
XLF_daily_returns =project_data['XLF'].pct_change()
XLK_daily_returns =project_data['XLK'].pct_change()
XLP_daily_returns =project_data['XLP'].pct_change()
XLU_daily_returns =project_data['XLU'].pct_change()
XLV_daily_returns =project_data['XLV'].pct_change()
FTSE_daily_returns =project_data['^FTSE'].pct_change()

In [3]:
# concating all the column returns into single datafram
data_returns=pd.DataFrame(AAPL_daily_returns)
data_returns.insert(1,"DXY",DX_NYB_daily_returns)
data_returns.insert(2,"HSI",HSI_daily_returns)
data_returns.insert(1,"QQQ",QQQ_daily_returns)
data_returns.insert(2,"XLE",XLE_daily_returns)
data_returns.insert(1,"XLF",XLF_daily_returns)
data_returns.insert(2,"XLK",XLK_daily_returns)
data_returns.insert(2,"XLP",XLP_daily_returns)
data_returns.insert(1,"XLU",XLU_daily_returns)
data_returns.insert(2,"XLV",XLV_daily_returns)
data_returns.insert(2,"FTSE",FTSE_daily_returns)

In [4]:
data_returns

,AAPL,XLU,FTSE,XLV,XLF,XLP,XLK,QQQ,XLE,DXY,HSI
Date,,,,,,,,,,,
2000-01-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2000-01-07,0.047369,0.008601,0.008934,0.012208,0.016552,0.063395,0.017456,0.123682,0.010686,0.001490,0.016657
2000-01-10,-0.017588,0.003411,0.015819,0.102255,-0.017639,-0.022436,0.037990,0.027778,-0.008348,0.001885,0.028730
2000-01-11,-0.051151,-0.010765,-0.013439,-0.026641,-0.016575,0.000000,-0.028335,-0.048649,0.001123,-0.004258,0.000877
2000-01-12,-0.059973,-0.010309,0.002132,-0.016618,0.019662,0.005246,-0.004253,-0.022016,-0.004485,0.000597,-0.009324
...,...,...,...,...,...,...,...,...,...,...,...
2020-11-23,-0.029743,0.000157,-0.002787,-0.002574,0.018764,0.000301,-0.000250,0.000035,0.070651,0.001299,0.001312
2020-11-24,0.011594,0.010700,0.015536,0.002949,0.035031,0.006765,0.013907,0.014050,0.051382,-0.003027,0.003851
2020-11-25,0.007467,0.002647,-0.006390,-0.003675,-0.003489,-0.000597,0.002136,0.006146,-0.023319,-0.002602,0.003069
2020-11-27,0.004826,-0.009938,-0.003677,0.009222,-0.003151,-0.000149,0.005327,0.009214,-0.011684,-0.002174,0.008433
2020-11-30,0.021100,-0.014429,-0.015924,0.002741,-0.020724,-0.000149,0.006685,0.002040,-0.055256,0.000872,-0.020569

In [5]:
#data_returns.to_csv("/Users/shriy/Documents/Project_Petrovic-main/Project_Petrovic-main/returns_data.csv", index=True)

In [6]:
data_returns[data_returns < 0] = -1
data_returns[data_returns > 0] = 1

In [7]:
data_returns

            AAPL  XLU  FTSE  XLV  XLF  XLP  XLK  QQQ  XLE  DXY  HSI
Date
2000-01-06   NaN  NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2000-01-07   1.0  1.0   1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
2000-01-10  -1.0  1.0   1.0  1.0 -1.0 -1.0  1.0  1.0 -1.0  1.0  1.0
2000-01-11  -1.0 -1.0  -1.0 -1.0 -1.0  0.0 -1.0 -1.0  1.0 -1.0  1.0
2000-01-12  -1.0 -1.0   1.0 -1.0  1.0  1.0 -1.0 -1.0 -1.0  1.0 -1.0
...          ...  ...   ...  ...  ...  ...  ...  ...  ...  ...  ...
2020-11-23  -1.0  1.0  -1.0 -1.0  1.0  1.0 -1.0  1.0  1.0  1.0  1.0
2020-11-24   1.0  1.0   1.0  1.0  1.0  1.0  1.0  1.0  1.0 -1.0  1.0
2020-11-25   1.0  1.0  -1.0 -1.0 -1.0 -1.0  1.0  1.0 -1.0 -1.0  1.0
2020-11-27   1.0 -1.0  -1.0  1.0 -1.0 -1.0  1.0  1.0 -1.0 -1.0  1.0
2020-11-30   1.0 -1.0  -1.0  1.0 -1.0 -1.0  1.0  1.0 -1.0  1.0 -1.0

[4989 rows x 11 columns]

In [8]:
data_returns.to_csv("/Users/shriy/Documents/Project_Petrovic-main/Project_Petrovic-main/returns_data_classified.csv", index=True)